name: FTP Deploy Website

on:
  push:
    branches:
      - distribution  # change to your default branch if it's not 'main'

jobs:
  build:
    name: Deploying via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0  # Use the latest version if available
      with:
        server: mu-coding.club
        username: mucode@mu-coding.club
        password: MineCraft271828
        local-dir: snowflake/mucodingwebsite/
